pipeline {
    agent { docker { image 'alpine:latest' } }
    stages {
        stage('build') {
            steps {
                sh 'echo "Started build stage!"'
                sh 'echo "Finished build stage!"'
            }
        }
    }
}